app/templates/documents.rb, spec/classes/document_search_spec.rb
@nickmarden this index settings change instructs Elasticsearch to store additional info in i14y indices that makes the highlighting logic faster and less resource intensive. It trades more storage needs for more efficient highlighting.
There were no index settings specs for me to change, but interestingly this change did break one spec. I think the new spec expectation is actually more reasonable than the old expectation. When someone searches for `"amazing spiderman"` (with quotes), the results before this change would involve both "amazing" and "spiderman" being highlighted individually. The results after this change involve both words being highlighted together as one big highlighted chunk. It doesn't matter on SERPs though because the result looks exactly the same when rendered …
=> [#155523550] Store positions offsets in the index for highlightable fields

app/classes/document_query.rb, spec/classes/document_search_spec.rb
Add a `field_value_factor` function to prefer documents with higher `click_count` values.
=> [SRCH-402] prefer documents with higher click_count values

app/classes/document_query.rb, spec/classes/document_search_spec.rb
This PR updates the date filtering to use the `changed` value instead of `created`.
=> SRCH-552 filter by changed

app/classes/document_query.rb, spec/classes/document_search_spec.rb
This PR changes the updates the default 'freshness' sorting and date sorting to use the `changed` rather than `created` value.
=> SRCH-29 sort by changed

app/models/document.rb, spec/models/document_spec.rb, spec/requests/api/v1/collections_spec.rb
This PR (into the `release/sort_by_changed_29` branch) sets the stage for sorting by `changed` instead of `created`. It sets `changed` to equal `created` in cases where a `changed` value is nil (or an empty string), but a `changed` value is present.
It also includes quite a bit of spec cleanup. `spec/requests/api/v1/collections_spec.rb` could still use some more work, but at a certain point I had to stop and move on with my actual story. :) (Note also that I left a number of the hashes with string keys in place, to be consistent with the values returned by the parsed JSON.)
=> SRCH-551 set "changed" as "created" when missing

app/controllers/api/v1/documents.rb, spec/requests/api/v1/documents_spec.rb
This PR allows I14y documents to be created with only a title, rather than requiring a title plus either content or a description. This will allow us to index pages that lack both parseable content and metadata.
=> SRCH-656 stop requiring content or description

spec/classes/document_search_spec.rb
This PR fixes the broken "sorting by date" spec on master. The issue was that the change I made to set `changed` to the value of `created` (https://github.com/GSA/i14y/commit/135f9192ef5a2fda22b0760f771b2107cf677e6c) meant that the doc that was supposed to have no value for `changed` was having that value set to its `created` date. The fix is to nullify `created` in the test doc.
=> SRCH-791 fix date sorting spec

.circleci/config.yml, app/classes/document_search_results.rb, spec/classes/document_search_spec.rb
This PR prevents suggestions from being returned when valid results are found for a query. It also resolves a couple of Rubocop offenses:
```
app/classes/document_search_results.rb:21:27: W: Lint/UselessAssignment: Useless assignment to variable - error.
rescue NoMethodError => error
^^^^^
app/classes/document_search_results.rb:37:24: C: Style/DateTime: Prefer Date or Time over DateTime.
source[date] = DateTime.parse(source[date]).utc.to_s if source[date].present?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> SRCH-706 do not return suggestion if search returns results

.circleci/config.yml
@peggles2 , this removes 2.3 from the test matrix on CirclCi. Tests will be run against ruby 2.5 and 2.6.
=> SRCH-811 remove ruby 2.3 from test matrix

app/templates/documents.rb
This PR updates the `bigrams` field from `string` (which was deprecated in ES 5) to `text`.
=> SRCH-1230 use text type for bigrams

app/templates/documents.rb
@peggles2 , this is a follow-up tweak to https://github.com/GSA/i14y/pull/108. I made two errors with that PR: 1) I didn't rebuild the templates before running my local specs, so my specs were passing erroneously, 2) I didn't realize the the branch had failed on CircleCi, which was hidden because the failure happened before the PR was opened. Oy. 
Anyway, this change is due to the fact that while `string` types are deprecated for field mappings,  `string` is still used in dynamic templates to specify what should happen with generic strings: https://www.elastic.co/guide/en/elasticsearch/reference/master/dynamic-templates.html#match-mapping-type
=> match 'string' mapping type

app/classes/document_query.rb
This PR specifies the `fvh` highlighter type ("fast vector highlighter"), which is a forward-compatible change intended to preserve the existing highlighter behavior when we upgrade to Elasticsearch 6.8.
=> SRCH-1233 specify highlighter type

Gemfile.lock, app/classes/document_query.rb, app/templates/documents.rb
This PR contains several changes designed to make I14y forward compatible with Elasticsearch 6.8.
=> Elasticsearch 6.8 compatibility

Gemfile.lock, app/classes/document_query.rb, app/templates/documents.rb
[SRCH-1230] - resolve search errors: 'no mapping found for field [bigrams]'
[SRCH-1233] - specify 'fvh' as highlighter type
[SRCH-1149] -update rack in i14y to 2.0.8+
=> Release 1.3.7

Gemfile.lock
[SRCH-1312] - Update Nokogiri security vulnerability for i14y.gov
=> Release 1.3.8

.circleci/config.yml, config/elasticsearch.yml, spec/rails_helper.rb
This PR updates our test environment to use Elasticsearch 6.8. (Note: I'm planning to clean this up when I tackle Dockerizing I14y. For now I am keeping it simple and just replacing the ES version # as necessary.) 
I'm adding a "do not merge" label until we're ready to upgrade to ES 6.8.
=> SRCH-1234 run specs against Elasticsearch 6.8

.circleci/config.yml, Dockerfile.elasticsearch, Gemfile.lock, README.md, config/elasticsearch.yml, docker-compose.yml
[SRCH-1031] - run Elasticsearch 6.8 using Docker
[SRCH-1541] - upgrade vulnerable i14y gems
=> Release 1.3.11

app/templates/collections.rb, app/templates/documents.rb
This resolves an ES 7 deprecation:
```
Deprecated field [template] used, replaced by [index_patterns] 
```
=> SRCH-1728 change 'template' to 'index_patterns'

app/templates/collections.rb, app/templates/documents.rb
This is the first of several minor tweaks resolving deprecation warnings, in preparation of our upgrade to Elasticsearch 7.x.
=> SRCH-1717 remove references to deprecated _all field

app/classes/document_query.rb
Negative weights in function scores are disallowed in Elasticsearch 7. This updates our function score to use a fractional value instead, which accomplishes the desired demotion of documents with certain filetypes.
=> SRCH-1716 use fractional weight to demote by extension

app/classes/document_search.rb, app/controllers/api/v1/collections.rb, config/initializers/elasticsearch.rb, lib/tasks/i14y.rake, spec/classes/document_search_spec.rb, spec/models/document_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/collections_spec.rb, spec/test_services.rb
This is the first of several PRs into the `release/elasticsearch_gems_1727` branch. I've broken up the changes largely to simplify the review process. This PR updates the Elasticsearch client initializer to avoid using the `Elasticsearch::Persistence.client` method, which is deprecated in the next version of the `elasticsearch-persistence` gem. That will still be in temporary use to set the persistence client (`Elasticsearch::Persistence.client = ES.client`) until I update the gems.
It also adds a couple of test helpers to DRY up the specs.
=> SRCH-1754 update Elasticsearch initializer & client

Gemfile, Gemfile.lock, spec/models/collection_spec.rb, spec/models/document_spec.rb, spec/requests/api/v1/collections_spec.rb, spec/requests/api/v1/documents_spec.rb, spec/support/document_crud.rb, spec/support/shoulda.rb
This PR adds some unit tests to simplify the upgrade process. (This repo is heavy on integration specs, light on unit specs.)
=> SRCH-1756 add additional specs

app/repositories/collection_repository.rb, app/repositories/document_repository.rb, spec/repositories/collection_repository_spec.rb, spec/repositories/document_repository_spec.rb, spec/support/shared_examples/repository_behavior.rb
This PR sets up the new Repository classes, which will subsequently be used to store the corresponding `Document` and `Collection` instances. The goal is to decouple the model logic from the persistence logic. A detailed explanation of why and how these changes are being made is in:
https://www.elastic.co/blog/activerecord-to-repository-changing-persistence-patterns-with-the-elasticsearch-rails-gem
The follow-up commits will build on these repository classes, moving the persistence, serialization, and search logic out of the `Document` and `Collection` classes and into the repository classes. (I toyed with retaining the `elasticsearch-model` gem, which offers ActiveRecord-y persistence to POROs, but ultimately I agree w/ the recommendation to decouple the model/ persistence logic. It …
=> SRCH-1743 create repository classes

.gitignore, spec/lib/serde_spec.rb, spec/models/collection_spec.rb, spec/models/document_spec.rb, spec/requests/api/v1/documents_spec.rb
'lil more spec refactoring. This PR:
- adds `.rspec-local` to `.gitignore`
- moves some of the serialization specs out of the document specs and into the serializer spec
- adds a few minor unit specs for the models
- moves the "created"/"changed" spec to the request spec, to ensure future refactoring doesn't break that specific functionality
=> SRCH-1767 refactor serialization specs

.gitignore, Gemfile, Gemfile.lock, app/classes/document_query.rb, app/templates/collections.rb, app/templates/documents.rb, spec/lib/serde_spec.rb, spec/models/collection_spec.rb, spec/models/document_spec.rb, spec/requests/api/v1/collections_spec.rb, spec/requests/api/v1/documents_spec.rb, spec/support/document_crud.rb, spec/support/shoulda.rb
https://github.com/GSA/i14y/pull/127 SRCH-1731 resolve deprecation errors in preparation for Elasticsearch
https://github.com/GSA/i14y/pull/129 SRCH-1756 add additional specs
https://github.com/GSA/i14y/pull/132 SRCH-1767 refactor serialization specs
=> Release 1.3.12

Gemfile, Gemfile.lock, app/classes/document_query.rb
This PR resolves the following breaking change:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_the_filter_context_has_been_removed
=> SRCH-1818 set minimum_should_match to 1 in bool filter

.circleci/config.yml, Dockerfile.elasticsearch6, Dockerfile.elasticsearch7
This PR:
- updates our CircleCI config to use their new text matrix syntax (https://circleci.com/blog/circleci-matrix-jobs/)
- adds Elasticsearch 7.10.1 to the test matrix
=> SRCH-1718 run specs against Elasticsearch 6 & 7

.circleci/config.yml, app/repositories/collection_repository.rb, app/repositories/concerns/repository.rb, app/repositories/document_repository.rb, spec/support/shared_examples/repository_behavior.rb
This PR ensures that objects instantiated when deserializing from Elasticsearch have the `id` populated from the Elasticsearch `_id` field. This is [recommended](https://www.elastic.co/blog/activerecord-to-repository-changing-persistence-patterns-with-the-elasticsearch-rails-gem) for the Repository pattern, and ensures that our code will work for documents created before our ES7 code changes. Also: 
- move common repository code to a shared concern
- wait for Elasticsearch before running specs in CircleCi
- clean up DocumentRepository#deserialize
=> SRCH-1854 set ID when deserializing

app/controllers/api/base.rb, app/controllers/api/v1/base.rb, app/controllers/api/v1/collections.rb, app/controllers/api/v1/documents.rb, config/application.rb, config/routes.rb, spec/requests/api/v1/collections_spec.rb, spec/requests/api/v1/documents_spec.rb
SRCH-2022 Renamed API module to Api to conform to zeitwerk's preferences.
=> SRCH-2022 use zeitwerk

.circleci/config.yml
SRCH-2640 remove Ruby 2.6 from CircleCi matrix
- use Ruby orb 1.4.0
=> SRCH-2640 remove Ruby 2.6 from CircleCi matrix

.github/pull_request_template.md
- removing requirement to squash commits before review
:warning: You have run `bundle update` and committed your changes to Gemfile.lock. - not doing this step
=> SRCH-3299 remove squash requirement

app/classes/document_query.rb, app/controllers/api/v1/collections.rb, spec/classes/document_search_spec.rb
- Adds (additional) facet field filtering to i14y document querying
- Builds on two filtering models already present in i14y.
- `language` is currently filterable via a text string; `audience`, `content_type`, and `mime_type` have been added.
- `tags` is currently filterable via an array of one or many comma-separated strings; `searchgov_custom1`, `searchgov_custom2`, and `searchgov_custom3` have been added.
- After running a an initial query that returns results, an additional filter can now be applied to winnow down those results based on facet field content.
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why …
=> SRCH-3477 i14y support filtering text facet fields

app/classes/document_query.rb, app/controllers/api/v1/collections.rb, spec/classes/document_search_spec.rb
- Adds (additional) facet field filtering to i14y document querying
- Filtering by `changed` date is already supported via the `min_timestamp` and `max_timestamp` params, this adds additional `min_timestamp_created` and `max_timestamp_created` params to filter by creation dates as well
- A follow-on ticket is being created to investigate the implications of renaming the existing params for greater clarity now that searchers can filter on both created and changed dates.
- After running a an initial query that returns results, date filters for changed (existing) and created (newly added) may be applied to winnow down those results based on facet field content.
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you …
=> SRCH-3478 i14y support filtering date facet fields

app/classes/document_query.rb, spec/classes/document_search_spec.rb
- Updates i14y so to include `audience` and `searchgov_custom`s in query matching;
- Extends existing logic for `tags` querying to the `searchgov_custom` fields (e.g. downcases search, requires exact match on term, etc.)
=> SRCH-3388 Search newly added i14y fields

.circleci/config.yml, README.md
This PR removes ElasticSearch 6 from the CI matrix and updates the README to reference ElasticSearch 7.
=> SRCH-1719 Make ElasticSearch 7 the default for development and testing

app/classes/document_query.rb, app/controllers/api/v1/collections.rb, spec/classes/document_search_spec.rb, spec/requests/api/v1/collections_spec.rb
- Changes i14y search behavior for filterable text facet fields (audience, content_type,  mime_type, searchgov_custom1, searchgov_custom2, searchgov_custom3, tags) to be ORed within a comma-separated list of provided text terms for a specific field;
- Maintains ANDing behavior across different fields;
- Includes new/modified specs to document this behavior in the first commit;
- The second commit wholly consists of spec refactoring for `spec/classes/document_search_spec.rb`.  With the additions necessary for this code change, that already exceedingly long and dense spec file was getting harder and harder to follow, particularly the myriad ways test data was being setup.  I've consolidated and re-orged to hopefully start moving the needle forward on making these tests easier to follow, but …
=> SRCH-3708 Or within filterable fields

config/initializers/elasticsearch.rb
This PR disables the `reload_on_connections` and `reload_on_failure` Elasticsearch client options in order to address an issue with ES connections in production.
=> SRCH-4594 Disable Elasticsearch discovery

config/environments/production.rb
- This PR makes a small change to production logs.
=> SRCH-5618: i14y production.log entries are going into puma.error.log instead
