GSA/i14y

Gemfile, Gemfile.lock, lib/tasks/fake.rake, spec/lib/tasks/fake_spec.rb
=> add rake task to generate fake documents

app/classes/document_query.rb, app/classes/document_search.rb, app/classes/query_parser.rb, spec/classes/document_search_spec.rb, spec/classes/query_parser_spec.rb
=> [Fixes #132112577] prevent suggestion searches from dropping domain

.circleci/config.yml, README.md, config/elasticsearch.yml, config/initializers/elasticsearch.rb
=> [#160521621] update README to allow devs to run multiple versions of

app/classes/document_query.rb, app/classes/document_search.rb, spec/classes/document_search_spec.rb
- send query errors to NewRelic
- log full query JSON for failed queries
=> SRCH-15 fix suggester bug

.circleci/config.yml, README.md, app/classes/document_query.rb, app/classes/document_search.rb, config/elasticsearch.yml, config/initializers/elasticsearch.rb, spec/classes/document_search_spec.rb
=> Prod push 20181010

.circleci/config.yml, README.md, app/classes/document_query.rb, app/classes/document_search.rb, config/elasticsearch.yml, config/initializers/elasticsearch.rb, spec/classes/document_search_spec.rb
=> Revert "Prod push 20181010"

app/classes/document_query.rb, app/classes/document_search.rb, spec/classes/document_search_spec.rb
This reverts commit cf218dfb39eee9a6a520c8d1926f063e03e9b33e.
=> Revert "SRCH-15 fix suggester bug (#52)"

app/classes/document_query.rb, app/classes/document_search.rb, spec/classes/document_query_spec.rb, spec/classes/document_search_spec.rb
SRCH-15 - Revert "SRCH-15 fix suggester bug"
SRCH-81 strip stopwords from suggester text
=> Release 1.0.2

app/classes/document_search.rb, spec/classes/document_search_spec.rb
- report query errors to NewRelic
=> SRCH-82 log full query JSON for failed queries

app/classes/document_search.rb, spec/classes/document_search_spec.rb
SRCH-82 log full query JSON for failed queries (#58)
=> Release 1.0.4

Gemfile.lock
[SRCH-210] - update rack to address security vulnerability
=> Release 1.0.7

app/controllers/api/v1/documents.rb, app/models/document.rb, app/templates/documents.rb, spec/requests/api/v1/documents_spec.rb
- allow click_count to be updated via the API
=> [#160332459] add click_count field to documents

app/controllers/api/v1/documents.rb, app/models/document.rb, app/templates/documents.rb, spec/requests/api/v1/documents_spec.rb
[SRCH-403] modify I14y API to update click_count field
=> Release 1.1.0

app/classes/document_query.rb, spec/classes/document_search_spec.rb
[SRCH-402] - prefer documents with higher click_count values
=> Release 1.2.0

app/classes/document_query.rb, app/models/document.rb, spec/classes/document_search_spec.rb, spec/models/document_spec.rb, spec/requests/api/v1/collections_spec.rb
[SRCH-552] - filter by changed
[SRCH-29]   -  sort by changed
[SRCH-551] - set "changed" as "created" when missing
=> Release 1.3.0

app/controllers/api/v1/documents.rb, spec/requests/api/v1/documents_spec.rb
[SRCH-656] - stop requiring content or description
=> Release 1.3.2

.circleci/config.yml, app/classes/document_search_results.rb, spec/classes/document_search_spec.rb
[SRCH-706] - do not return suggestion if search returns results
[SRCH-791] - fix date sorting spec
[SRCH-811] - remove ruby 2.3 from test matrix
=> Release 1.3.3

.circleci/config.yml, Dockerfile.elasticsearch, README.md, config/elasticsearch.yml, docker-compose.yml
- add Basic Usage instructions to README
=> SRCH-1031 run Elasticsearch 6.8 using Docker

app/classes/document_query.rb, app/templates/collections.rb, app/templates/documents.rb
@jmax-fearless , this is the first batch of changes for the ES 7 upgrade. The changes have already been reviewed in other PRs, so this just requires a quick sanity check to verify that nothing untoward has snuck into the release branch.
=> SRCH-1731 resolve deprecation errors in preparation for Elasticsearch 7

app/classes/document_search.rb
This PR handles the breaking change mentioned in the comment.
=> SRCH-1819 return total search hits as an integer

app/controllers/api/v1/collections.rb, app/repositories/collection_repository.rb, app/repositories/document_repository.rb, app/templates/collections.rb, app/templates/documents.rb, lib/tasks/i14y.rake, spec/classes/document_search_spec.rb, spec/support/shared_examples/repository_behavior.rb
This PR updates the templates for compatibility with ES7:
- set include_type_name parameter for index & template creation
- specify # of shards & replicas
- update template mappings
- add spec for shard/replica count
=> SRCH-1730 update templates

app/models/collection.rb, app/models/document.rb
This PR resolves several stylistic issues identified by CodeClimate:
https://codeclimate.com/github/GSA/i14y/pull/131
=> SRCH-1822 placate Rubocop

.circleci/config.yml
Also switched parameters to matrix syntax.
=> SRCH-2220 Remove Ruby 2.5 from i14y CircleCi

Gemfile, Gemfile.lock, config/newrelic.yml
SRCH-2170 Bump newrelic_apm gem from 4.2 -> 6.15.0
=> SRCH-2170 Bump newrelic_apm gem from 4.2 -> 6.15.0

.circleci/config.yml, Gemfile, Gemfile.lock, config/newrelic.yml
Functional:
SRCH-2170 update newrelic gem (#166) 
Testing:
SRCH-2220 Remove Ruby 2.5 from i14y CircleCi (#154)
=> Release 1.3.17

.circleci/config.yml, Gemfile.lock
SRCH-2403 use bundler 2.2.24 (#171)
- bump CircleCi ruby orb
=> Release 2.0.1

Gemfile.lock
- Upgrades to bundler 2.3.8
- Repo uses most recent CircleCI Ruby Orb so no further action needed there
N/A
N/A
=> SRCH-2865 Upgrade to bundler 2.3.8

Gemfile.lock
- SRCH-2865 Upgrade to bundler 2.3.8
=> Release - SRCH-2865

.github/pull_request_template.md, config/deploy.rb
- Renaming 'master' branch to 'main': update comment in config/deploy.rb and text in .github/pull_request_template.md.
=> SRCH-3008: Update i14y to use main

.codeinventory.yml
- Updating email address to new email (search@gsa.gov)
=> SRCH-3070 update email in .codeinventory.yml

.codeinventory.yml, .github/pull_request_template.md, Gemfile.lock, config/deploy.rb
Functional
- [SRCH-3104 Bump rack from 2.2.3 to 2.2.3.1](https://github.com/GSA/i14y/commit/80f56ab5c4a9f4bac6a4d39fdd3c45e9863475c7)
Housekeeping
- [SRCH-3070 update email in .codeinventory.yml](https://github.com/GSA/i14y/commit/67ebf3260c052ad7eb9957f49d968dd3e2c43bb9)
- [SRCH-3008: Update i14y to use main](https://github.com/GSA/i14y/commit/3770dd70d712cbbf02875a3ab506931be69f0a45)
No manual testing
=> Release - SRCH-3104

.github/pull_request_template.md
- Updating the PR template per team discussions
- I'm _not_ running a bundle update as part of these changes; if we want to do that, we can assign a dev to these changes.
- Template below reflects the proposed changes (manually pasted in for now)
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji.
⚠️  You have run `bundle update` and committed your changes to Gemfile.lock. - **N/A - not running bundle update**
=> SRCH-3168 update PR template

.codeclimate.yml, Gemfile.lock, app/controllers/api/v1/documents.rb, app/models/document.rb, app/templates/documents.rb, spec/models/document_spec.rb, spec/requests/api/v1/documents_spec.rb
* SRCH-3111 - update I14y to save the document's MIME type
- ⚠️  Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.
Minor syntax difference.  Visually OK but Jira will not catch it since not capitalized and joined with a dash.  So picky that Jira....
=> Release - SRCH-3111

Gemfile, Gemfile.lock
This PR adds the `debug` gem. I tested adding a breakpoint in a test, and the gem worked as expected.
=> SRCH-3428 Add `debug` gem

Gemfile, Gemfile.lock
- SRCH-3428 Add `debug` gem (#208)
=> Release - SRCH-3428

app/templates/documents.rb, config/initializers/locales.rb, lib/serde.rb, spec/classes/document_search_spec.rb, spec/lib/serde_spec.rb, spec/requests/api/v1/documents_spec.rb
- [SRCH-3375 Treat custom fields as arrays](https://github.com/GSA/i14y/commit/9e6b7ca15160ae6c92c49e09ceb6c5166656cea0)
- [SRCH-3351 language support for built-in languages (Hindi and Bengali)](https://github.com/GSA/i14y/commit/272754649743eaf85868575f0faef7f10179ad91)
=> Release - SRCH-3375, SRCH-3351

.github/pull_request_template.md
Remove bundle update requirement
=> SRCH-3461 Update PR template

.rubocop.yml, Gemfile.lock, app/classes/document_query.rb, app/classes/document_search_results.rb, spec/classes/document_query_spec.rb, spec/classes/document_search_spec.rb, spec/requests/api/v1/collections_spec.rb
- [SRCH-3468 Date-based aggregations](https://github.com/GSA/i14y/commit/8d8798b43021259c2ce323a462242cc84136a59b)
=> Release - SRCH-3468

app/classes/document_query.rb, app/controllers/api/v1/collections.rb, spec/classes/document_search_spec.rb
- [SRCH-3477 i14y support filtering text facet fields](https://github.com/GSA/i14y/commit/ca75204a4e64c8854c96b1925cb75dd1a38be4d0)
- [SRCH-3478 i14y support filtering date facet fields](https://github.com/GSA/i14y/commit/130c594e6daa5bb815be2576a6f1fcc2cb08d964)
=> Release - SRCH-3477, SRCH-3478

spec/classes/document_search_spec.rb
- Includes small fix to tests in `spec/classes/document_search_spec.rb`
- Previously failure showing the issue: https://app.circleci.com/pipelines/github/GSA/i14y/193/workflows/8a8fb7e9-00f4-499a-87e5-f225654a870b/jobs/737
- For the purposes of these tests, we don't care what order the results are returned, we only care that those (and only those) results are returned.
=> SRCH-3621 fix flaky date filtering specs

app/classes/document_query.rb, spec/classes/document_search_spec.rb
- [SRCH-3388 Search newly added i14y fields](https://github.com/GSA/i14y/commit/ac40aae27307001cebeb08f5ddfb352b77be88f8)
- [SRCH-3621 fix flaky date filtering specs](https://github.com/GSA/i14y/commit/07c6db662ac6014954d86a8446522d612b87de15)
=> Release - SRCH-3388, SRCH-3621

app/classes/document_query.rb, app/controllers/api/v1/collections.rb, spec/classes/document_search_spec.rb, spec/requests/api/v1/collections_spec.rb
- SRCH-3708 Or within filterable fields (#238)
=> Release - SRCH-3708

.circleci/config.yml
This PR bumps the versions of Ruby tested in CircleCI.
=> SRCH-3911 test against Ruby 3.0.5 and 3.1.3

.circleci/config.yml, app/controllers/api/v1/documents.rb, app/models/document.rb, app/templates/documents.rb, spec/models/document_spec.rb, spec/requests/api/v1/documents_spec.rb
- [SRCH-3687 Add thumbnail_url to i14y](https://github.com/GSA/i14y/commit/6ee53c6309f5f011149446346f7ac5b1af06907c)
- [SRCH-3911 test against Ruby 3.0.5 and 3.1.3](https://github.com/GSA/i14y/commit/c7bfa4ab1bc7394f174da2d19acd3174e6e0af01)
=> Release - SRCH-3687, SRCH-3911

Gemfile.lock
This PR upgrades bundler to the latest version.
=> SRCH-3840 Upgrade bundler in i14y

Gemfile.lock
- SRCH-3840 Upgrade bundler in i14y
=> Release - SRCH-3840

app/classes/document_query.rb, spec/classes/document_search_spec.rb, spec/requests/api/v1/collections_spec.rb
- Return the `thumbnail_url` field along with default fields.
=> SRCH-3690 Add thumbnail_url to default return fields in i14y

app/classes/document_query.rb, spec/classes/document_search_spec.rb, spec/requests/api/v1/collections_spec.rb
- SRCH-3690 Add image_url to default return fields in i14y
=> Release- SRCH-3690

config/initializers/filter_parameter_logging.rb, spec/config/initializers/filter_parameter_logging_spec.rb
- SRCH-3933 Filter query from request params in log
=> Release - SRCH-3933

.dockerignore, Dockerfile, config/application.rb, config/environments/test.rb
- Add a Dockerfile and the configuration to the i14y.
- i14y service will be created and run using docker-compose.yml in search-services. Refer to https://github.com/GSA/search-services/pull/10
=> SRCH-4119 Dockerize i14y development

README.md
- Updated ReadMe for using i14y within docker.
=> SRCH-4120 Update i14y README about using docker

config/initializers/elasticsearch.rb
SRCH-4304 Enable TLS for Elasticsearch connections
=> SRCH-4304 Enable TLS for Elasticsearch connections

config/initializers/elasticsearch.rb
- [SRCH-4304 Enable TLS for Elasticsearch connections](https://github.com/GSA/i14y/commit/c411e9a8ea3bccf2910c7af6df403c6111edf4e0)
=> Release - SRCH-4304

config/environments/production.rb
This PR reverts the log configuration changes in production environment during the Rails 7 upgrade.
=> SRCH-4366 Revert log configuration in production environment.

config/environments/production.rb
- SRCH-4510 Force SSL in production
- SRCH-4366 Revert log configuration in production environment
=> Release  SRCH-4510, SRCH-4366

config/application.rb
-  This PR addresses a post rails upgrade deployment configuration. We explicitly state the cache format version in the `application.rb` file. 
=> SRCH-4372 Add cache format version.

config/application.rb
* SRCH-4372 Add cache format version.
* SRCH 4372 Revert deletion of comments.
=> Release - SRCH-4372 

Gemfile.lock
- SRCH-5026 Bump rdoc from 6.6.1 to 6.6.3.1 
=> Release - SRCH-5026 Bump rdoc from 6.6.1 to 6.6.3.1

config/initializers/elasticsearch.rb
- This PR reverts changes to elastic search regarding an environment variable based on this ticket: https://cm-jira.usa.gov/browse/SRCH-5091
=> SRCH-5091: Revert environment variable change.

.circleci/config.yml, config/environments/development.rb
- Removes older versions of ruby from circle ci matrix; adds target 3.3.0 version (as optional) to matrix
- Corrects local dev configuration issue
=> SRCH-4969 Update circleci ruby version

.circleci/config.yml
- Adds ruby 3.1.4 to the circleci test matrix
=> SRCH-5098 Add 3.1.4 to test matrix

bin/secure_docker
- Fix suid & sgid deletion, remove crontabs and init files
=> SRCH-5267 fix suid & sgid deletion, remove contabs and init files

.circleci/config.yml, bin/secure_docker
- SRCH-5267 fix suid & sgid deletion, remove contabs and init files
=> Release - SRCH-5267 fix suid & sgid deletion, remove contabs and init files

Dockerfile, app/controllers/api/v1/collections.rb, config/environments/production.rb
- Update ruby version
- Fix issue with secrets
- Log to STOUT in docker
=> SRCH-5221 Fix ruby version, fix logs, and fix secrets in docker.

.circleci/config.yml
=> SRCH-5020 image pipeline

.circleci/config.yml, Dockerfile, app/controllers/api/v1/collections.rb, config/environments/production.rb
- SRCH-5221 Fix ruby version, fix logs, and fix secrets in docker.
- SRCH-5020 image pipeline
=> Release - SRCH-5221, SRCH-5020 

.circleci/config.yml
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
=> SRCH-5252 Removing custom ES image

.circleci/config.yml
- SRCH-5334 uncommenting out EKS code
=> SRCH-5334 uncommenting out EKS code

appspec.yml, buildspec_asis.yml, cicd-scripts/fetch_env_vars.sh
-added cicd scripts
- [ x] You have merged the latest changes from the target branch (usually `main`) into your branch.
- [ x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.
- [ x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
- [ x] Automated checks pass. If Code Climate checks do not …
=> Srch-5391 codepipeline

config/environments/production.rb
- This PR adds the following host to production environment: `i14y.search.usa.gov`
=> Add Production Host URL

config/environments/production.rb
=> Add Production Host URL (#335)

config/environments/production.rb
- This PR adds a different operator to the host config.
=> Change operator to host domains

cicd-scripts/fetch_env_vars.sh
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
=> Sync with staging (#341)

cicd-scripts/fetch_env_vars.sh, config/environments/production.rb
- This PR syncs latest staging with man
=> Sync staging with main

config/newrelic.yml
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
=> SRCH-5619 setup newrelic

config/deploy.rb
- Use I14Y_THREADS and I14Y_WORKERS to setup puma
=> SRCH-5617 Parameterize puma settings

config/elasticsearch.yml
- Update log_level with env variable in `elasticsearch.yml`.
=> SRCH-5732 Update ES log_level with env variable for i14y

config/elasticsearch.yml, config/initializers/elasticsearch.rb
- This PR releases changes in `staging` to `production`
=> Staging to production

Gemfile, Gemfile.lock
- Do not upgrade capistrano3-puma gem due issues with deployment
=> SRCH-5808 Lock capistrano3-puma version
